---
version: '3'

services:

  fluentd:
    build: .
    image: index.docker.io/oaklabs/component-telegraf:${VERSION-latest}
    volumes:
      - ./config:/config:ro
      - ./secrets:/secrets:ro
    environment:
      TELEGRAF_CONFIG: '/conf/google-telegraf.conf'
      INFLUXDB_HOST: 'http://influxdb.oak.host:8086'
      GOOGLE_ZONE: 'us-east1-b'
      GOOGLE_APPLICATION_CREDENTIALS: '/secrets/default-credentials.json'
