---
version: '3'

services:

  telegraf:
    build: .
    image: index.docker.io/oaklabs/component-telegraf:${VERSION-latest}
    volumes:
      - ./config:/config:ro
      - ./secrets:/secrets:ro
    environment:
      TELEGRAF_CONFIG: 'google-telegraf.conf'
      INFLUXDB_HOST: ''
      AWS_TOKEN: ''
      BUCKET: ''
      GOOGLE_ZONE: 'us-east1-b'
      GOOGLE_APPLICATION_CREDENTIALS: '/secrets/default-credentials.json'
